# File Path: pubspec.yaml

name: pharmacy_app
description: A Hospital Management System with Django HMS backend

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Backend & Database
  dio: ^5.4.0

  # Security & Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # UI & Icons
  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  
  # Utilities
  intl: ^0.19.0
  
  # File Operations & Permissions
  csv: ^6.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/1.png
    - assets/images/2.png